import { useEffect } from "react";
import { useTranscriptStore } from "@/lib/store";
import { TranscriptEditor } from "../TranscriptEditor";

// todo: remove mock functionality
const mockTranscript = {
  segments: [
    {
      id: "seg-1",
      speaker: "SPEAKER_00",
      start: 0.5,
      end: 4.2,
      text: "Hello and welcome to our podcast today. I am excited to have you here.",
      words: [
        { word: "Hello", start: 0.5, end: 0.8 },
        { word: "and", start: 0.85, end: 1.0 },
        { word: "welcome", start: 1.05, end: 1.4 },
        { word: "to", start: 1.45, end: 1.55 },
        { word: "our", start: 1.6, end: 1.75 },
        { word: "podcast", start: 1.8, end: 2.2 },
        { word: "today.", start: 2.25, end: 2.6 },
        { word: "I", start: 2.7, end: 2.8 },
        { word: "am", start: 2.85, end: 2.95 },
        { word: "excited", start: 3.0, end: 3.4 },
        { word: "to", start: 3.45, end: 3.55 },
        { word: "have", start: 3.6, end: 3.75 },
        { word: "you", start: 3.8, end: 3.9 },
        { word: "here.", start: 3.95, end: 4.2 },
      ],
    },
    {
      id: "seg-2",
      speaker: "SPEAKER_01",
      start: 4.8,
      end: 9.5,
      text: "Thank you so much for having me. It is a pleasure to be here and discuss this topic.",
      words: [
        { word: "Thank", start: 4.8, end: 5.1 },
        { word: "you", start: 5.15, end: 5.3 },
        { word: "so", start: 5.35, end: 5.5 },
        { word: "much", start: 5.55, end: 5.75 },
        { word: "for", start: 5.8, end: 5.95 },
        { word: "having", start: 6.0, end: 6.35 },
        { word: "me.", start: 6.4, end: 6.65 },
        { word: "It", start: 6.8, end: 6.9 },
        { word: "is", start: 6.95, end: 7.1 },
        { word: "a", start: 7.15, end: 7.25 },
        { word: "pleasure", start: 7.3, end: 7.7 },
        { word: "to", start: 7.75, end: 7.85 },
        { word: "be", start: 7.9, end: 8.0 },
        { word: "here", start: 8.05, end: 8.25 },
        { word: "and", start: 8.3, end: 8.45 },
        { word: "discuss", start: 8.5, end: 8.85 },
        { word: "this", start: 8.9, end: 9.05 },
        { word: "topic.", start: 9.1, end: 9.5 },
      ],
    },
    {
      id: "seg-3",
      speaker: "SPEAKER_00",
      start: 10.2,
      end: 15.8,
      text: "Absolutely. So let us dive right in. Can you tell our listeners a bit about your background?",
      words: [
        { word: "Absolutely.", start: 10.2, end: 10.8 },
        { word: "So", start: 10.95, end: 11.1 },
        { word: "let", start: 11.15, end: 11.3 },
        { word: "us", start: 11.35, end: 11.5 },
        { word: "dive", start: 11.55, end: 11.85 },
        { word: "right", start: 11.9, end: 12.15 },
        { word: "in.", start: 12.2, end: 12.5 },
        { word: "Can", start: 12.7, end: 12.9 },
        { word: "you", start: 12.95, end: 13.1 },
        { word: "tell", start: 13.15, end: 13.35 },
        { word: "our", start: 13.4, end: 13.55 },
        { word: "listeners", start: 13.6, end: 14.1 },
        { word: "a", start: 14.15, end: 14.25 },
        { word: "bit", start: 14.3, end: 14.5 },
        { word: "about", start: 14.55, end: 14.8 },
        { word: "your", start: 14.85, end: 15.05 },
        { word: "background?", start: 15.1, end: 15.8 },
      ],
    },
    {
      id: "seg-4",
      speaker: "SPEAKER_01",
      start: 16.5,
      end: 25.0,
      text: "Of course. I have been working in this field for over fifteen years now. It all started when I was a student at university.",
      words: [
        { word: "Of", start: 16.5, end: 16.65 },
        { word: "course.", start: 16.7, end: 17.1 },
        { word: "I", start: 17.3, end: 17.4 },
        { word: "have", start: 17.45, end: 17.6 },
        { word: "been", start: 17.65, end: 17.85 },
        { word: "working", start: 17.9, end: 18.3 },
        { word: "in", start: 18.35, end: 18.5 },
        { word: "this", start: 18.55, end: 18.75 },
        { word: "field", start: 18.8, end: 19.1 },
        { word: "for", start: 19.15, end: 19.3 },
        { word: "over", start: 19.35, end: 19.6 },
        { word: "fifteen", start: 19.65, end: 20.1 },
        { word: "years", start: 20.15, end: 20.5 },
        { word: "now.", start: 20.55, end: 20.9 },
        { word: "It", start: 21.1, end: 21.2 },
        { word: "all", start: 21.25, end: 21.45 },
        { word: "started", start: 21.5, end: 21.95 },
        { word: "when", start: 22.0, end: 22.2 },
        { word: "I", start: 22.25, end: 22.35 },
        { word: "was", start: 22.4, end: 22.6 },
        { word: "a", start: 22.65, end: 22.75 },
        { word: "student", start: 22.8, end: 23.2 },
        { word: "at", start: 23.25, end: 23.4 },
        { word: "university.", start: 23.45, end: 25.0 },
      ],
    },
    {
      id: "seg-5",
      speaker: "SPEAKER_02",
      start: 25.8,
      end: 30.2,
      text: "That is really interesting. I had a similar experience when I started my career.",
      words: [
        { word: "That", start: 25.8, end: 26.0 },
        { word: "is", start: 26.05, end: 26.2 },
        { word: "really", start: 26.25, end: 26.6 },
        { word: "interesting.", start: 26.65, end: 27.3 },
        { word: "I", start: 27.5, end: 27.6 },
        { word: "had", start: 27.65, end: 27.85 },
        { word: "a", start: 27.9, end: 28.0 },
        { word: "similar", start: 28.05, end: 28.5 },
        { word: "experience", start: 28.55, end: 29.1 },
        { word: "when", start: 29.15, end: 29.35 },
        { word: "I", start: 29.4, end: 29.5 },
        { word: "started", start: 29.55, end: 29.9 },
        { word: "my", start: 29.95, end: 30.05 },
        { word: "career.", start: 30.1, end: 30.2 },
      ],
    },
  ],
};

export default function TranscriptEditorExample() {
  const { loadTranscript } = useTranscriptStore();

  useEffect(() => {
    loadTranscript({ segments: mockTranscript.segments });
  }, [loadTranscript]);

  return <TranscriptEditor />;
}
